### ISSUE TITLE
Vcs Server stability

### ISSUE THREAD

**Issue by James-Crean** [CDAT/vcs-js#35]
When using vcdat for more than a few minutes, the server seems to either crash or get killed. It is unclear exactly what causes it, but does not seem to be solely caused by user interaction. After leaving the app open for a few minutes without activity, it no longer works as well.

**Comment by scottwittenburg** [comment]
I cannot reproduce this with the simple demo that lives in this repository, but maybe I could do so with the vcdat application.  Is there a basic description of how to run that application somewhere in the vcdat repo?

**Comment by James-Crean** [comment]
There are instructions in the wiki for installing, but the basic instructions to install as a developer is to clone the repo, CD into the directory and run ./scripts/setup.sh. Then, `source activate nightly` followed by `./scripts/autorun.sh`.

Be aware that I believe there is an issue with webpack right now, so if you get a JavaScript error that prevents the application from loading, do a git checkout to 4a655b72.

**Comment by scottwittenburg** [comment]
Thanks @James-Crean, though I wasn't able to find the instructions on the wiki, the steps you listed above were enough for me to be able to run the web application.  I did, indeed, need to checkout the alternate sha in order for it to work.  I'll let you know once I'm able to reproduce the crash of the server.

**Comment by James-Crean** [comment]
Thanks for letting me know that the documentation is missing. I'll update it first thing tomorrow.
 The crash I run into tends to be a segmentation fault if that helps. It may be a bug inside vcs rather than anything in vcsjs, but I don't know vcsjs well enough to troubleshoot it efficiently. Thanks again for looking into this.

**Comment by scottwittenburg** [comment]
Well, the documentation might not be missing, I just didn't find it.  I looked around in [here](https://github.com/UV-CDAT/uvcdat/wiki), maybe that's the wrong wiki though?

**Comment by James-Crean** [comment]
Ah, yeah. The vCDAT repo has it's own wiki. The readme needs a link to it so people can find it.

**Comment by scottwittenburg** [comment]
Well, I did a lot of testing with the `vcdat` application yesterday (which is pretty cool by the way).  I even left it running overnight and it was still responding this morning when I got back into the office.  Is there any extra information I might need to be able to reproduce this issue?

By the way, while I was testing I ran into that isoline plot failure you mentioned somewhere recently (related to `numpy.isfinite(x)` to help trigger your memory).  I did some debugging and found the problem there, but I haven't cooked up the right solution yet.  However, I can't seem to find that issue anywhere, do you remember where that was?

**Comment by James-Crean** [comment]
It was buried inside another issue. I created a proper issue for it [here](https://github.com/UV-CDAT/vcdat/issues/195).

Hmm... I'll see if i can't find a way to make it crash consistently so that you can reproduce it. I'll update you when I have something definitive.

**Comment by James-Crean** [comment]
The server seems to be much less likely to crash these days. Closing this.
